apiVersion: v1
kind: PersistentVolume
metadata:
  name: coredns-zones
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  hostPath:
    path: /tmp/coredns-zones
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coredns-zones
  namespace: coredns-netbox
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
  storageClassName: ""
  volumeName: coredns-zones
