apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: coredns-netbox
servers: 1
agents: 0
ports:
  - port: 15353:53/tcp
    nodeFilters:
      - loadbalancer
  - port: 15353:53/udp
    nodeFilters:
      - loadbalancer
  - port: 15354:5354/tcp
    nodeFilters:
      - loadbalancer
  - port: 15354:5354/udp
    nodeFilters:
      - loadbalancer
volumes:
  - volume: ${HOME}/.local/share/coredns-netbox/pgdata:/pgdata
    nodeFilters:
      - server:0
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
