apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coredns-netbox.fullname" . }}
  labels:
    {{- include "coredns-netbox.labels" . | nindent 4 }}
data:
  Corefile: |
    . {
        auto {
            directory {{ .Values.zoneDir }} db\.(.*) {1}
            reload 10s
        }
        {{- if or .Values.transfer.to .Values.transfer.notify }}
        transfer {
            {{- range .Values.transfer.to }}
            to {{ . }}
            {{- end }}
            {{- if .Values.transfer.notify }}
            notify {{ join " " .Values.transfer.notify }}
            {{- end }}
        }
        {{- end }}
        forward . {{ range .Values.forwardServers }}{{ . }} {{ end }}
        cache {{ .Values.cacheTTL }}
        log
        errors
        health :8080
        ready :8181
        {{- if .Values.metrics.enabled }}
        prometheus :{{ .Values.metrics.port }}
        {{- end }}
    }
{{- if .Values.secondary.enabled }}
  Corefile-secondary: |
    {{- range .Values.secondary.zones }}
    {{ . }} {
        secondary {
            {{- range $.Values.secondary.transferFrom }}
            transfer from {{ . }}
            {{- end }}
        }
    }
    {{- end }}
    . {
        forward . {{ range $.Values.forwardServers }}{{ . }} {{ end }}
        cache {{ .Values.cacheTTL }}
        log
        errors
        health :8080
        ready :8181
    }
{{- end }}
