{{- if not .Values.netbox.existingSecret }}
{{- if not .Values.netbox.token }}
  {{- fail "Either netbox.token or netbox.existingSecret must be set" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coredns-netbox.fullname" . }}
  labels:
    {{- include "coredns-netbox.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.netbox.token | quote }}
{{- end }}
