// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/coredns_netbox/v1/zones.proto

package netboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DnsName       string                 `protobuf:"bytes,1,opt,name=dns_name,json=dnsName,proto3" json:"dns_name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Family        int32                  `protobuf:"varint,3,opt,name=family,proto3" json:"family,omitempty"`
	Ttl           uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetDnsName() string {
	if x != nil {
		return x.DnsName
	}
	return ""
}

func (x *Record) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Record) GetFamily() int32 {
	if x != nil {
		return x.Family
	}
	return 0
}

func (x *Record) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type CreateZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateZoneRequest) Reset() {
	*x = CreateZoneRequest{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateZoneRequest) ProtoMessage() {}

func (x *CreateZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateZoneRequest.ProtoReflect.Descriptor instead.
func (*CreateZoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{1}
}

func (x *CreateZoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateZoneResponse) Reset() {
	*x = CreateZoneResponse{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateZoneResponse) ProtoMessage() {}

func (x *CreateZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateZoneResponse.ProtoReflect.Descriptor instead.
func (*CreateZoneResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{2}
}

type DeleteZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteZoneRequest) Reset() {
	*x = DeleteZoneRequest{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteZoneRequest) ProtoMessage() {}

func (x *DeleteZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteZoneRequest.ProtoReflect.Descriptor instead.
func (*DeleteZoneRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteZoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteZoneResponse) Reset() {
	*x = DeleteZoneResponse{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteZoneResponse) ProtoMessage() {}

func (x *DeleteZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteZoneResponse.ProtoReflect.Descriptor instead.
func (*DeleteZoneResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{4}
}

type ListZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListZonesRequest) Reset() {
	*x = ListZonesRequest{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZonesRequest) ProtoMessage() {}

func (x *ListZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZonesRequest.ProtoReflect.Descriptor instead.
func (*ListZonesRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{5}
}

type ListZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListZonesResponse) Reset() {
	*x = ListZonesResponse{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZonesResponse) ProtoMessage() {}

func (x *ListZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZonesResponse.ProtoReflect.Descriptor instead.
func (*ListZonesResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{6}
}

func (x *ListZonesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type UpsertRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRecordRequest) Reset() {
	*x = UpsertRecordRequest{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRecordRequest) ProtoMessage() {}

func (x *UpsertRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRecordRequest.ProtoReflect.Descriptor instead.
func (*UpsertRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertRecordRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *UpsertRecordRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *UpsertRecordRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type UpsertRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRecordResponse) Reset() {
	*x = UpsertRecordResponse{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRecordResponse) ProtoMessage() {}

func (x *UpsertRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRecordResponse.ProtoReflect.Descriptor instead.
func (*UpsertRecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{8}
}

type DeleteRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	DnsName       string                 `protobuf:"bytes,2,opt,name=dns_name,json=dnsName,proto3" json:"dns_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRecordRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *DeleteRecordRequest) GetDnsName() string {
	if x != nil {
		return x.DnsName
	}
	return ""
}

type DeleteRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordResponse) Reset() {
	*x = DeleteRecordResponse{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordResponse) ProtoMessage() {}

func (x *DeleteRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{10}
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{11}
}

func (x *ListRecordsRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type ListRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{12}
}

func (x *ListRecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type ZoneRecords struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Records       []*Record              `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneRecords) Reset() {
	*x = ZoneRecords{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneRecords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneRecords) ProtoMessage() {}

func (x *ZoneRecords) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneRecords.ProtoReflect.Descriptor instead.
func (*ZoneRecords) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{13}
}

func (x *ZoneRecords) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *ZoneRecords) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type BatchUpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneRecords   []*ZoneRecords         `protobuf:"bytes,1,rep,name=zone_records,json=zoneRecords,proto3" json:"zone_records,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpsertRequest) Reset() {
	*x = BatchUpsertRequest{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertRequest) ProtoMessage() {}

func (x *BatchUpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertRequest.ProtoReflect.Descriptor instead.
func (*BatchUpsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{14}
}

func (x *BatchUpsertRequest) GetZoneRecords() []*ZoneRecords {
	if x != nil {
		return x.ZoneRecords
	}
	return nil
}

func (x *BatchUpsertRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type BatchUpsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpsertResponse) Reset() {
	*x = BatchUpsertResponse{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertResponse) ProtoMessage() {}

func (x *BatchUpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertResponse.ProtoReflect.Descriptor instead.
func (*BatchUpsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{15}
}

type BatchDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	DnsNames      []string               `protobuf:"bytes,2,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteRequest) Reset() {
	*x = BatchDeleteRequest{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteRequest) ProtoMessage() {}

func (x *BatchDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{16}
}

func (x *BatchDeleteRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *BatchDeleteRequest) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

type BatchDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteResponse) Reset() {
	*x = BatchDeleteResponse{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteResponse) ProtoMessage() {}

func (x *BatchDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteResponse.ProtoReflect.Descriptor instead.
func (*BatchDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{17}
}

type ForceNetboxPollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceNetboxPollRequest) Reset() {
	*x = ForceNetboxPollRequest{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceNetboxPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceNetboxPollRequest) ProtoMessage() {}

func (x *ForceNetboxPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceNetboxPollRequest.ProtoReflect.Descriptor instead.
func (*ForceNetboxPollRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{18}
}

type ForceNetboxPollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceNetboxPollResponse) Reset() {
	*x = ForceNetboxPollResponse{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceNetboxPollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceNetboxPollResponse) ProtoMessage() {}

func (x *ForceNetboxPollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceNetboxPollResponse.ProtoReflect.Descriptor instead.
func (*ForceNetboxPollResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{19}
}

type ForceMergeWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceMergeWriteRequest) Reset() {
	*x = ForceMergeWriteRequest{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceMergeWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceMergeWriteRequest) ProtoMessage() {}

func (x *ForceMergeWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceMergeWriteRequest.ProtoReflect.Descriptor instead.
func (*ForceMergeWriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{20}
}

type ForceMergeWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceMergeWriteResponse) Reset() {
	*x = ForceMergeWriteResponse{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceMergeWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceMergeWriteResponse) ProtoMessage() {}

func (x *ForceMergeWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceMergeWriteResponse.ProtoReflect.Descriptor instead.
func (*ForceMergeWriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{21}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{22}
}

type GetStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LastNetboxPollUnix   int64                  `protobuf:"varint,1,opt,name=last_netbox_poll_unix,json=lastNetboxPollUnix,proto3" json:"last_netbox_poll_unix,omitempty"`
	LastMergeWriteUnix   int64                  `protobuf:"varint,2,opt,name=last_merge_write_unix,json=lastMergeWriteUnix,proto3" json:"last_merge_write_unix,omitempty"`
	ActiveZones          int32                  `protobuf:"varint,3,opt,name=active_zones,json=activeZones,proto3" json:"active_zones,omitempty"`
	DynamicRecordCount   int32                  `protobuf:"varint,4,opt,name=dynamic_record_count,json=dynamicRecordCount,proto3" json:"dynamic_record_count,omitempty"`
	ZoneStalenessSeconds float64                `protobuf:"fixed64,5,opt,name=zone_staleness_seconds,json=zoneStalenessSeconds,proto3" json:"zone_staleness_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{23}
}

func (x *GetStatusResponse) GetLastNetboxPollUnix() int64 {
	if x != nil {
		return x.LastNetboxPollUnix
	}
	return 0
}

func (x *GetStatusResponse) GetLastMergeWriteUnix() int64 {
	if x != nil {
		return x.LastMergeWriteUnix
	}
	return 0
}

func (x *GetStatusResponse) GetActiveZones() int32 {
	if x != nil {
		return x.ActiveZones
	}
	return 0
}

func (x *GetStatusResponse) GetDynamicRecordCount() int32 {
	if x != nil {
		return x.DynamicRecordCount
	}
	return 0
}

func (x *GetStatusResponse) GetZoneStalenessSeconds() float64 {
	if x != nil {
		return x.ZoneStalenessSeconds
	}
	return 0
}

type ZoneReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneReloadRequest) Reset() {
	*x = ZoneReloadRequest{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneReloadRequest) ProtoMessage() {}

func (x *ZoneReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneReloadRequest.ProtoReflect.Descriptor instead.
func (*ZoneReloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{24}
}

type ZoneReloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneReloadResponse) Reset() {
	*x = ZoneReloadResponse{}
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneReloadResponse) ProtoMessage() {}

func (x *ZoneReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredns_netbox_v1_zones_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneReloadResponse.ProtoReflect.Descriptor instead.
func (*ZoneReloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP(), []int{25}
}

var File_proto_coredns_netbox_v1_zones_proto protoreflect.FileDescriptor

const file_proto_coredns_netbox_v1_zones_proto_rawDesc = "" +
	"\n" +
	"#proto/coredns_netbox/v1/zones.proto\x12\x11coredns_netbox.v1\"g\n" +
	"\x06Record\x12\x19\n" +
	"\bdns_name\x18\x01 \x01(\tR\adnsName\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06family\x18\x03 \x01(\x05R\x06family\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\"'\n" +
	"\x11CreateZoneRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x14\n" +
	"\x12CreateZoneResponse\"'\n" +
	"\x11DeleteZoneRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x14\n" +
	"\x12DeleteZoneResponse\"\x12\n" +
	"\x10ListZonesRequest\")\n" +
	"\x11ListZonesResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"r\n" +
	"\x13UpsertRecordRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x121\n" +
	"\x06record\x18\x02 \x01(\v2\x19.coredns_netbox.v1.RecordR\x06record\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\x16\n" +
	"\x14UpsertRecordResponse\"D\n" +
	"\x13DeleteRecordRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x19\n" +
	"\bdns_name\x18\x02 \x01(\tR\adnsName\"\x16\n" +
	"\x14DeleteRecordResponse\"(\n" +
	"\x12ListRecordsRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\"J\n" +
	"\x13ListRecordsResponse\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.coredns_netbox.v1.RecordR\arecords\"V\n" +
	"\vZoneRecords\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x123\n" +
	"\arecords\x18\x02 \x03(\v2\x19.coredns_netbox.v1.RecordR\arecords\"m\n" +
	"\x12BatchUpsertRequest\x12A\n" +
	"\fzone_records\x18\x01 \x03(\v2\x1e.coredns_netbox.v1.ZoneRecordsR\vzoneRecords\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x15\n" +
	"\x13BatchUpsertResponse\"E\n" +
	"\x12BatchDeleteRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x1b\n" +
	"\tdns_names\x18\x02 \x03(\tR\bdnsNames\"\x15\n" +
	"\x13BatchDeleteResponse\"\x18\n" +
	"\x16ForceNetboxPollRequest\"\x19\n" +
	"\x17ForceNetboxPollResponse\"\x18\n" +
	"\x16ForceMergeWriteRequest\"\x19\n" +
	"\x17ForceMergeWriteResponse\"\x12\n" +
	"\x10GetStatusRequest\"\x84\x02\n" +
	"\x11GetStatusResponse\x121\n" +
	"\x15last_netbox_poll_unix\x18\x01 \x01(\x03R\x12lastNetboxPollUnix\x121\n" +
	"\x15last_merge_write_unix\x18\x02 \x01(\x03R\x12lastMergeWriteUnix\x12!\n" +
	"\factive_zones\x18\x03 \x01(\x05R\vactiveZones\x120\n" +
	"\x14dynamic_record_count\x18\x04 \x01(\x05R\x12dynamicRecordCount\x124\n" +
	"\x16zone_staleness_seconds\x18\x05 \x01(\x01R\x14zoneStalenessSeconds\"\x13\n" +
	"\x11ZoneReloadRequest\"\x14\n" +
	"\x12ZoneReloadResponse2\xfe\x05\n" +
	"\x12DynamicZoneService\x12Y\n" +
	"\n" +
	"CreateZone\x12$.coredns_netbox.v1.CreateZoneRequest\x1a%.coredns_netbox.v1.CreateZoneResponse\x12Y\n" +
	"\n" +
	"DeleteZone\x12$.coredns_netbox.v1.DeleteZoneRequest\x1a%.coredns_netbox.v1.DeleteZoneResponse\x12V\n" +
	"\tListZones\x12#.coredns_netbox.v1.ListZonesRequest\x1a$.coredns_netbox.v1.ListZonesResponse\x12_\n" +
	"\fUpsertRecord\x12&.coredns_netbox.v1.UpsertRecordRequest\x1a'.coredns_netbox.v1.UpsertRecordResponse\x12_\n" +
	"\fDeleteRecord\x12&.coredns_netbox.v1.DeleteRecordRequest\x1a'.coredns_netbox.v1.DeleteRecordResponse\x12\\\n" +
	"\vListRecords\x12%.coredns_netbox.v1.ListRecordsRequest\x1a&.coredns_netbox.v1.ListRecordsResponse\x12\\\n" +
	"\vBatchUpsert\x12%.coredns_netbox.v1.BatchUpsertRequest\x1a&.coredns_netbox.v1.BatchUpsertResponse\x12\\\n" +
	"\vBatchDelete\x12%.coredns_netbox.v1.BatchDeleteRequest\x1a&.coredns_netbox.v1.BatchDeleteResponse2\xbc\x02\n" +
	"\x0eControlService\x12h\n" +
	"\x0fForceNetboxPoll\x12).coredns_netbox.v1.ForceNetboxPollRequest\x1a*.coredns_netbox.v1.ForceNetboxPollResponse\x12h\n" +
	"\x0fForceMergeWrite\x12).coredns_netbox.v1.ForceMergeWriteRequest\x1a*.coredns_netbox.v1.ForceMergeWriteResponse\x12V\n" +
	"\tGetStatus\x12#.coredns_netbox.v1.GetStatusRequest\x1a$.coredns_netbox.v1.GetStatusResponse2j\n" +
	"\x11ZoneReloadService\x12U\n" +
	"\x06Reload\x12$.coredns_netbox.v1.ZoneReloadRequest\x1a%.coredns_netbox.v1.ZoneReloadResponseBFZDgithub.com/pallotron/coredns-netbox/proto/coredns_netbox/v1;netboxv1b\x06proto3"

var (
	file_proto_coredns_netbox_v1_zones_proto_rawDescOnce sync.Once
	file_proto_coredns_netbox_v1_zones_proto_rawDescData []byte
)

func file_proto_coredns_netbox_v1_zones_proto_rawDescGZIP() []byte {
	file_proto_coredns_netbox_v1_zones_proto_rawDescOnce.Do(func() {
		file_proto_coredns_netbox_v1_zones_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coredns_netbox_v1_zones_proto_rawDesc), len(file_proto_coredns_netbox_v1_zones_proto_rawDesc)))
	})
	return file_proto_coredns_netbox_v1_zones_proto_rawDescData
}

var file_proto_coredns_netbox_v1_zones_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_coredns_netbox_v1_zones_proto_goTypes = []any{
	(*Record)(nil),                  // 0: coredns_netbox.v1.Record
	(*CreateZoneRequest)(nil),       // 1: coredns_netbox.v1.CreateZoneRequest
	(*CreateZoneResponse)(nil),      // 2: coredns_netbox.v1.CreateZoneResponse
	(*DeleteZoneRequest)(nil),       // 3: coredns_netbox.v1.DeleteZoneRequest
	(*DeleteZoneResponse)(nil),      // 4: coredns_netbox.v1.DeleteZoneResponse
	(*ListZonesRequest)(nil),        // 5: coredns_netbox.v1.ListZonesRequest
	(*ListZonesResponse)(nil),       // 6: coredns_netbox.v1.ListZonesResponse
	(*UpsertRecordRequest)(nil),     // 7: coredns_netbox.v1.UpsertRecordRequest
	(*UpsertRecordResponse)(nil),    // 8: coredns_netbox.v1.UpsertRecordResponse
	(*DeleteRecordRequest)(nil),     // 9: coredns_netbox.v1.DeleteRecordRequest
	(*DeleteRecordResponse)(nil),    // 10: coredns_netbox.v1.DeleteRecordResponse
	(*ListRecordsRequest)(nil),      // 11: coredns_netbox.v1.ListRecordsRequest
	(*ListRecordsResponse)(nil),     // 12: coredns_netbox.v1.ListRecordsResponse
	(*ZoneRecords)(nil),             // 13: coredns_netbox.v1.ZoneRecords
	(*BatchUpsertRequest)(nil),      // 14: coredns_netbox.v1.BatchUpsertRequest
	(*BatchUpsertResponse)(nil),     // 15: coredns_netbox.v1.BatchUpsertResponse
	(*BatchDeleteRequest)(nil),      // 16: coredns_netbox.v1.BatchDeleteRequest
	(*BatchDeleteResponse)(nil),     // 17: coredns_netbox.v1.BatchDeleteResponse
	(*ForceNetboxPollRequest)(nil),  // 18: coredns_netbox.v1.ForceNetboxPollRequest
	(*ForceNetboxPollResponse)(nil), // 19: coredns_netbox.v1.ForceNetboxPollResponse
	(*ForceMergeWriteRequest)(nil),  // 20: coredns_netbox.v1.ForceMergeWriteRequest
	(*ForceMergeWriteResponse)(nil), // 21: coredns_netbox.v1.ForceMergeWriteResponse
	(*GetStatusRequest)(nil),        // 22: coredns_netbox.v1.GetStatusRequest
	(*GetStatusResponse)(nil),       // 23: coredns_netbox.v1.GetStatusResponse
	(*ZoneReloadRequest)(nil),       // 24: coredns_netbox.v1.ZoneReloadRequest
	(*ZoneReloadResponse)(nil),      // 25: coredns_netbox.v1.ZoneReloadResponse
}
var file_proto_coredns_netbox_v1_zones_proto_depIdxs = []int32{
	0,  // 0: coredns_netbox.v1.UpsertRecordRequest.record:type_name -> coredns_netbox.v1.Record
	0,  // 1: coredns_netbox.v1.ListRecordsResponse.records:type_name -> coredns_netbox.v1.Record
	0,  // 2: coredns_netbox.v1.ZoneRecords.records:type_name -> coredns_netbox.v1.Record
	13, // 3: coredns_netbox.v1.BatchUpsertRequest.zone_records:type_name -> coredns_netbox.v1.ZoneRecords
	1,  // 4: coredns_netbox.v1.DynamicZoneService.CreateZone:input_type -> coredns_netbox.v1.CreateZoneRequest
	3,  // 5: coredns_netbox.v1.DynamicZoneService.DeleteZone:input_type -> coredns_netbox.v1.DeleteZoneRequest
	5,  // 6: coredns_netbox.v1.DynamicZoneService.ListZones:input_type -> coredns_netbox.v1.ListZonesRequest
	7,  // 7: coredns_netbox.v1.DynamicZoneService.UpsertRecord:input_type -> coredns_netbox.v1.UpsertRecordRequest
	9,  // 8: coredns_netbox.v1.DynamicZoneService.DeleteRecord:input_type -> coredns_netbox.v1.DeleteRecordRequest
	11, // 9: coredns_netbox.v1.DynamicZoneService.ListRecords:input_type -> coredns_netbox.v1.ListRecordsRequest
	14, // 10: coredns_netbox.v1.DynamicZoneService.BatchUpsert:input_type -> coredns_netbox.v1.BatchUpsertRequest
	16, // 11: coredns_netbox.v1.DynamicZoneService.BatchDelete:input_type -> coredns_netbox.v1.BatchDeleteRequest
	18, // 12: coredns_netbox.v1.ControlService.ForceNetboxPoll:input_type -> coredns_netbox.v1.ForceNetboxPollRequest
	20, // 13: coredns_netbox.v1.ControlService.ForceMergeWrite:input_type -> coredns_netbox.v1.ForceMergeWriteRequest
	22, // 14: coredns_netbox.v1.ControlService.GetStatus:input_type -> coredns_netbox.v1.GetStatusRequest
	24, // 15: coredns_netbox.v1.ZoneReloadService.Reload:input_type -> coredns_netbox.v1.ZoneReloadRequest
	2,  // 16: coredns_netbox.v1.DynamicZoneService.CreateZone:output_type -> coredns_netbox.v1.CreateZoneResponse
	4,  // 17: coredns_netbox.v1.DynamicZoneService.DeleteZone:output_type -> coredns_netbox.v1.DeleteZoneResponse
	6,  // 18: coredns_netbox.v1.DynamicZoneService.ListZones:output_type -> coredns_netbox.v1.ListZonesResponse
	8,  // 19: coredns_netbox.v1.DynamicZoneService.UpsertRecord:output_type -> coredns_netbox.v1.UpsertRecordResponse
	10, // 20: coredns_netbox.v1.DynamicZoneService.DeleteRecord:output_type -> coredns_netbox.v1.DeleteRecordResponse
	12, // 21: coredns_netbox.v1.DynamicZoneService.ListRecords:output_type -> coredns_netbox.v1.ListRecordsResponse
	15, // 22: coredns_netbox.v1.DynamicZoneService.BatchUpsert:output_type -> coredns_netbox.v1.BatchUpsertResponse
	17, // 23: coredns_netbox.v1.DynamicZoneService.BatchDelete:output_type -> coredns_netbox.v1.BatchDeleteResponse
	19, // 24: coredns_netbox.v1.ControlService.ForceNetboxPoll:output_type -> coredns_netbox.v1.ForceNetboxPollResponse
	21, // 25: coredns_netbox.v1.ControlService.ForceMergeWrite:output_type -> coredns_netbox.v1.ForceMergeWriteResponse
	23, // 26: coredns_netbox.v1.ControlService.GetStatus:output_type -> coredns_netbox.v1.GetStatusResponse
	25, // 27: coredns_netbox.v1.ZoneReloadService.Reload:output_type -> coredns_netbox.v1.ZoneReloadResponse
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_coredns_netbox_v1_zones_proto_init() }
func file_proto_coredns_netbox_v1_zones_proto_init() {
	if File_proto_coredns_netbox_v1_zones_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coredns_netbox_v1_zones_proto_rawDesc), len(file_proto_coredns_netbox_v1_zones_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_coredns_netbox_v1_zones_proto_goTypes,
		DependencyIndexes: file_proto_coredns_netbox_v1_zones_proto_depIdxs,
		MessageInfos:      file_proto_coredns_netbox_v1_zones_proto_msgTypes,
	}.Build()
	File_proto_coredns_netbox_v1_zones_proto = out.File
	file_proto_coredns_netbox_v1_zones_proto_goTypes = nil
	file_proto_coredns_netbox_v1_zones_proto_depIdxs = nil
}
