// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/coredns_netbox/v1/zones.proto

package netboxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DynamicZoneService_CreateZone_FullMethodName   = "/coredns_netbox.v1.DynamicZoneService/CreateZone"
	DynamicZoneService_DeleteZone_FullMethodName   = "/coredns_netbox.v1.DynamicZoneService/DeleteZone"
	DynamicZoneService_ListZones_FullMethodName    = "/coredns_netbox.v1.DynamicZoneService/ListZones"
	DynamicZoneService_UpsertRecord_FullMethodName = "/coredns_netbox.v1.DynamicZoneService/UpsertRecord"
	DynamicZoneService_DeleteRecord_FullMethodName = "/coredns_netbox.v1.DynamicZoneService/DeleteRecord"
	DynamicZoneService_ListRecords_FullMethodName  = "/coredns_netbox.v1.DynamicZoneService/ListRecords"
	DynamicZoneService_BatchUpsert_FullMethodName  = "/coredns_netbox.v1.DynamicZoneService/BatchUpsert"
	DynamicZoneService_BatchDelete_FullMethodName  = "/coredns_netbox.v1.DynamicZoneService/BatchDelete"
)

// DynamicZoneServiceClient is the client API for DynamicZoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DynamicZoneServiceClient interface {
	CreateZone(ctx context.Context, in *CreateZoneRequest, opts ...grpc.CallOption) (*CreateZoneResponse, error)
	DeleteZone(ctx context.Context, in *DeleteZoneRequest, opts ...grpc.CallOption) (*DeleteZoneResponse, error)
	ListZones(ctx context.Context, in *ListZonesRequest, opts ...grpc.CallOption) (*ListZonesResponse, error)
	UpsertRecord(ctx context.Context, in *UpsertRecordRequest, opts ...grpc.CallOption) (*UpsertRecordResponse, error)
	DeleteRecord(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error)
	ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsResponse, error)
	BatchUpsert(ctx context.Context, in *BatchUpsertRequest, opts ...grpc.CallOption) (*BatchUpsertResponse, error)
	BatchDelete(ctx context.Context, in *BatchDeleteRequest, opts ...grpc.CallOption) (*BatchDeleteResponse, error)
}

type dynamicZoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamicZoneServiceClient(cc grpc.ClientConnInterface) DynamicZoneServiceClient {
	return &dynamicZoneServiceClient{cc}
}

func (c *dynamicZoneServiceClient) CreateZone(ctx context.Context, in *CreateZoneRequest, opts ...grpc.CallOption) (*CreateZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateZoneResponse)
	err := c.cc.Invoke(ctx, DynamicZoneService_CreateZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicZoneServiceClient) DeleteZone(ctx context.Context, in *DeleteZoneRequest, opts ...grpc.CallOption) (*DeleteZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteZoneResponse)
	err := c.cc.Invoke(ctx, DynamicZoneService_DeleteZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicZoneServiceClient) ListZones(ctx context.Context, in *ListZonesRequest, opts ...grpc.CallOption) (*ListZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListZonesResponse)
	err := c.cc.Invoke(ctx, DynamicZoneService_ListZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicZoneServiceClient) UpsertRecord(ctx context.Context, in *UpsertRecordRequest, opts ...grpc.CallOption) (*UpsertRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertRecordResponse)
	err := c.cc.Invoke(ctx, DynamicZoneService_UpsertRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicZoneServiceClient) DeleteRecord(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRecordResponse)
	err := c.cc.Invoke(ctx, DynamicZoneService_DeleteRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicZoneServiceClient) ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecordsResponse)
	err := c.cc.Invoke(ctx, DynamicZoneService_ListRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicZoneServiceClient) BatchUpsert(ctx context.Context, in *BatchUpsertRequest, opts ...grpc.CallOption) (*BatchUpsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpsertResponse)
	err := c.cc.Invoke(ctx, DynamicZoneService_BatchUpsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicZoneServiceClient) BatchDelete(ctx context.Context, in *BatchDeleteRequest, opts ...grpc.CallOption) (*BatchDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchDeleteResponse)
	err := c.cc.Invoke(ctx, DynamicZoneService_BatchDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamicZoneServiceServer is the server API for DynamicZoneService service.
// All implementations must embed UnimplementedDynamicZoneServiceServer
// for forward compatibility.
type DynamicZoneServiceServer interface {
	CreateZone(context.Context, *CreateZoneRequest) (*CreateZoneResponse, error)
	DeleteZone(context.Context, *DeleteZoneRequest) (*DeleteZoneResponse, error)
	ListZones(context.Context, *ListZonesRequest) (*ListZonesResponse, error)
	UpsertRecord(context.Context, *UpsertRecordRequest) (*UpsertRecordResponse, error)
	DeleteRecord(context.Context, *DeleteRecordRequest) (*DeleteRecordResponse, error)
	ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsResponse, error)
	BatchUpsert(context.Context, *BatchUpsertRequest) (*BatchUpsertResponse, error)
	BatchDelete(context.Context, *BatchDeleteRequest) (*BatchDeleteResponse, error)
	mustEmbedUnimplementedDynamicZoneServiceServer()
}

// UnimplementedDynamicZoneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDynamicZoneServiceServer struct{}

func (UnimplementedDynamicZoneServiceServer) CreateZone(context.Context, *CreateZoneRequest) (*CreateZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateZone not implemented")
}
func (UnimplementedDynamicZoneServiceServer) DeleteZone(context.Context, *DeleteZoneRequest) (*DeleteZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteZone not implemented")
}
func (UnimplementedDynamicZoneServiceServer) ListZones(context.Context, *ListZonesRequest) (*ListZonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListZones not implemented")
}
func (UnimplementedDynamicZoneServiceServer) UpsertRecord(context.Context, *UpsertRecordRequest) (*UpsertRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertRecord not implemented")
}
func (UnimplementedDynamicZoneServiceServer) DeleteRecord(context.Context, *DeleteRecordRequest) (*DeleteRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRecord not implemented")
}
func (UnimplementedDynamicZoneServiceServer) ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecords not implemented")
}
func (UnimplementedDynamicZoneServiceServer) BatchUpsert(context.Context, *BatchUpsertRequest) (*BatchUpsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUpsert not implemented")
}
func (UnimplementedDynamicZoneServiceServer) BatchDelete(context.Context, *BatchDeleteRequest) (*BatchDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDelete not implemented")
}
func (UnimplementedDynamicZoneServiceServer) mustEmbedUnimplementedDynamicZoneServiceServer() {}
func (UnimplementedDynamicZoneServiceServer) testEmbeddedByValue()                            {}

// UnsafeDynamicZoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynamicZoneServiceServer will
// result in compilation errors.
type UnsafeDynamicZoneServiceServer interface {
	mustEmbedUnimplementedDynamicZoneServiceServer()
}

func RegisterDynamicZoneServiceServer(s grpc.ServiceRegistrar, srv DynamicZoneServiceServer) {
	// If the following call panics, it indicates UnimplementedDynamicZoneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DynamicZoneService_ServiceDesc, srv)
}

func _DynamicZoneService_CreateZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicZoneServiceServer).CreateZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicZoneService_CreateZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicZoneServiceServer).CreateZone(ctx, req.(*CreateZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicZoneService_DeleteZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicZoneServiceServer).DeleteZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicZoneService_DeleteZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicZoneServiceServer).DeleteZone(ctx, req.(*DeleteZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicZoneService_ListZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListZonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicZoneServiceServer).ListZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicZoneService_ListZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicZoneServiceServer).ListZones(ctx, req.(*ListZonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicZoneService_UpsertRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicZoneServiceServer).UpsertRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicZoneService_UpsertRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicZoneServiceServer).UpsertRecord(ctx, req.(*UpsertRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicZoneService_DeleteRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicZoneServiceServer).DeleteRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicZoneService_DeleteRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicZoneServiceServer).DeleteRecord(ctx, req.(*DeleteRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicZoneService_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicZoneServiceServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicZoneService_ListRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicZoneServiceServer).ListRecords(ctx, req.(*ListRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicZoneService_BatchUpsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicZoneServiceServer).BatchUpsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicZoneService_BatchUpsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicZoneServiceServer).BatchUpsert(ctx, req.(*BatchUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicZoneService_BatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicZoneServiceServer).BatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicZoneService_BatchDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicZoneServiceServer).BatchDelete(ctx, req.(*BatchDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DynamicZoneService_ServiceDesc is the grpc.ServiceDesc for DynamicZoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DynamicZoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coredns_netbox.v1.DynamicZoneService",
	HandlerType: (*DynamicZoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateZone",
			Handler:    _DynamicZoneService_CreateZone_Handler,
		},
		{
			MethodName: "DeleteZone",
			Handler:    _DynamicZoneService_DeleteZone_Handler,
		},
		{
			MethodName: "ListZones",
			Handler:    _DynamicZoneService_ListZones_Handler,
		},
		{
			MethodName: "UpsertRecord",
			Handler:    _DynamicZoneService_UpsertRecord_Handler,
		},
		{
			MethodName: "DeleteRecord",
			Handler:    _DynamicZoneService_DeleteRecord_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _DynamicZoneService_ListRecords_Handler,
		},
		{
			MethodName: "BatchUpsert",
			Handler:    _DynamicZoneService_BatchUpsert_Handler,
		},
		{
			MethodName: "BatchDelete",
			Handler:    _DynamicZoneService_BatchDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coredns_netbox/v1/zones.proto",
}

const (
	ControlService_ForceNetboxPoll_FullMethodName = "/coredns_netbox.v1.ControlService/ForceNetboxPoll"
	ControlService_ForceMergeWrite_FullMethodName = "/coredns_netbox.v1.ControlService/ForceMergeWrite"
	ControlService_GetStatus_FullMethodName       = "/coredns_netbox.v1.ControlService/GetStatus"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	ForceNetboxPoll(ctx context.Context, in *ForceNetboxPollRequest, opts ...grpc.CallOption) (*ForceNetboxPollResponse, error)
	ForceMergeWrite(ctx context.Context, in *ForceMergeWriteRequest, opts ...grpc.CallOption) (*ForceMergeWriteResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) ForceNetboxPoll(ctx context.Context, in *ForceNetboxPollRequest, opts ...grpc.CallOption) (*ForceNetboxPollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceNetboxPollResponse)
	err := c.cc.Invoke(ctx, ControlService_ForceNetboxPoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ForceMergeWrite(ctx context.Context, in *ForceMergeWriteRequest, opts ...grpc.CallOption) (*ForceMergeWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceMergeWriteResponse)
	err := c.cc.Invoke(ctx, ControlService_ForceMergeWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, ControlService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
type ControlServiceServer interface {
	ForceNetboxPoll(context.Context, *ForceNetboxPollRequest) (*ForceNetboxPollResponse, error)
	ForceMergeWrite(context.Context, *ForceMergeWriteRequest) (*ForceMergeWriteResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) ForceNetboxPoll(context.Context, *ForceNetboxPollRequest) (*ForceNetboxPollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceNetboxPoll not implemented")
}
func (UnimplementedControlServiceServer) ForceMergeWrite(context.Context, *ForceMergeWriteRequest) (*ForceMergeWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceMergeWrite not implemented")
}
func (UnimplementedControlServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_ForceNetboxPoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceNetboxPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ForceNetboxPoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ForceNetboxPoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ForceNetboxPoll(ctx, req.(*ForceNetboxPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ForceMergeWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceMergeWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ForceMergeWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ForceMergeWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ForceMergeWrite(ctx, req.(*ForceMergeWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coredns_netbox.v1.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForceNetboxPoll",
			Handler:    _ControlService_ForceNetboxPoll_Handler,
		},
		{
			MethodName: "ForceMergeWrite",
			Handler:    _ControlService_ForceMergeWrite_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ControlService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coredns_netbox/v1/zones.proto",
}

const (
	ZoneReloadService_Reload_FullMethodName = "/coredns_netbox.v1.ZoneReloadService/Reload"
)

// ZoneReloadServiceClient is the client API for ZoneReloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZoneReloadServiceClient interface {
	Reload(ctx context.Context, in *ZoneReloadRequest, opts ...grpc.CallOption) (*ZoneReloadResponse, error)
}

type zoneReloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZoneReloadServiceClient(cc grpc.ClientConnInterface) ZoneReloadServiceClient {
	return &zoneReloadServiceClient{cc}
}

func (c *zoneReloadServiceClient) Reload(ctx context.Context, in *ZoneReloadRequest, opts ...grpc.CallOption) (*ZoneReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZoneReloadResponse)
	err := c.cc.Invoke(ctx, ZoneReloadService_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZoneReloadServiceServer is the server API for ZoneReloadService service.
// All implementations must embed UnimplementedZoneReloadServiceServer
// for forward compatibility.
type ZoneReloadServiceServer interface {
	Reload(context.Context, *ZoneReloadRequest) (*ZoneReloadResponse, error)
	mustEmbedUnimplementedZoneReloadServiceServer()
}

// UnimplementedZoneReloadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZoneReloadServiceServer struct{}

func (UnimplementedZoneReloadServiceServer) Reload(context.Context, *ZoneReloadRequest) (*ZoneReloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedZoneReloadServiceServer) mustEmbedUnimplementedZoneReloadServiceServer() {}
func (UnimplementedZoneReloadServiceServer) testEmbeddedByValue()                           {}

// UnsafeZoneReloadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZoneReloadServiceServer will
// result in compilation errors.
type UnsafeZoneReloadServiceServer interface {
	mustEmbedUnimplementedZoneReloadServiceServer()
}

func RegisterZoneReloadServiceServer(s grpc.ServiceRegistrar, srv ZoneReloadServiceServer) {
	// If the following call panics, it indicates UnimplementedZoneReloadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZoneReloadService_ServiceDesc, srv)
}

func _ZoneReloadService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneReloadServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneReloadService_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneReloadServiceServer).Reload(ctx, req.(*ZoneReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZoneReloadService_ServiceDesc is the grpc.ServiceDesc for ZoneReloadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZoneReloadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coredns_netbox.v1.ZoneReloadService",
	HandlerType: (*ZoneReloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reload",
			Handler:    _ZoneReloadService_Reload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coredns_netbox/v1/zones.proto",
}
