apiVersion: v2
name: coredns-netbox
description: CoreDNS with Netbox-backed DNS zone via sidecar zone file generator
version: 0.1.0
appVersion: "0.1.0"
type: application
home: https://github.com/pallotron/coredns-netbox
sources:
  - https://github.com/pallotron/coredns-netbox
keywords:
  - coredns
  - netbox
  - dns
  - ipam
maintainers:
  - name: pallotron
    url: https://github.com/pallotron
